### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by lkh329** [xguo7/NEC-DGT#1]
I really appreciate your work and thanks for sharing the code. 
I wonder if the data used in your paper is available?

**Comment by xguo7** [comment]
Hi,

Please find the relevant datasets here: https://github.com/xguo7/Dataset-for-Deep-Graph-Translation.
I have just updated the links in the Github. Thank you for your reminder.

Best,
Xiaojie
________________________________

**Comment by lkh329** [comment]
Thanks for your help!

Best,

Kehan
